//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace front_end_kpl.Language {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("front_end_kpl.Language.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Floor.
        /// </summary>
        internal static string ColumnRoomFloor {
            get {
                return ResourceManager.GetString("ColumnRoomFloor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room ID.
        /// </summary>
        internal static string ColumnRoomId {
            get {
                return ResourceManager.GetString("ColumnRoomId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string ColumnRoomName {
            get {
                return ResourceManager.GetString("ColumnRoomName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number.
        /// </summary>
        internal static string ColumnRoomNumber {
            get {
                return ResourceManager.GetString("ColumnRoomNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Floor.
        /// </summary>
        internal static string LableFloor {
            get {
                return ResourceManager.GetString("LableFloor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string LableName {
            get {
                return ResourceManager.GetString("LableName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number.
        /// </summary>
        internal static string LableNumber {
            get {
                return ResourceManager.GetString("LableNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name Empty.
        /// </summary>
        internal static string MNameEmpty {
            get {
                return ResourceManager.GetString("MNameEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room Added Successfuly.
        /// </summary>
        internal static string MRoomAddedSucces {
            get {
                return ResourceManager.GetString("MRoomAddedSucces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room Deleted Successfully.
        /// </summary>
        internal static string MRoomDeletedSucces {
            get {
                return ResourceManager.GetString("MRoomDeletedSucces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room with this floor and number already exists.
        /// </summary>
        internal static string MRoomExist {
            get {
                return ResourceManager.GetString("MRoomExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room with this id does not exists.
        /// </summary>
        internal static string MRoomNotExist {
            get {
                return ResourceManager.GetString("MRoomNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room Not Found.
        /// </summary>
        internal static string MRoomNotFound {
            get {
                return ResourceManager.GetString("MRoomNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room Updated Successfully.
        /// </summary>
        internal static string MRoomUpdatedSucces {
            get {
                return ResourceManager.GetString("MRoomUpdatedSucces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room Management.
        /// </summary>
        internal static string TitleRoom {
            get {
                return ResourceManager.GetString("TitleRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
    }
}
